language: java
jdk: oraclejdk8
before_script:
  - mysql -uroot -e "create database sample"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO root@localhost IDENTIFIED BY 'password' WITH GRANT OPTION"
script:
  - gradle flywayClean
  - gradle flywaymigrate
  - gradle test

