language: java
jdk: oraclejdk8
env:
- TERM=dumb
before_script:
  - mysql -uroot -e "create database sample"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO root@localhost IDENTIFIED BY 'password' WITH GRANT OPTION"
script:
  - ./gradlew flywaymigrate
  - ./gradlew test
  - ./gradlew check
  - ./gradlew build
after_success:
- ./gradlew jacocoTestReport coveralls

