language: java
jdk: oraclejdk8
env:
- TERM=dumb
before_script:
  - mysql -uroot -e "create database sample"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO root@localhost IDENTIFIED BY 'password' WITH GRANT OPTION"
script:
  - ./gradlew flywayClean
  - ./gradlew flywaymigrate
  - ./gradlew build
  - ./gradlew test
after_success:
- COVERALLS_REPO_TOKEN=4rtBJna06rkMNuZD1NTowvMfSwKN14s6U ./gradlew cobertura coveralls

